#!/bin/bash
#
#

set -e

trap 'cleanup_on_err' ERR EXIT

## Environment

PATH=/usr/sbin:/usr/local/bin:/usr/bin:/bin:$PATH

MSG_PREFIX="[lit-os-init > PRIME  ]"
STATE_FILE="/var/local/litos-init-prepare.install"

# Unused atm.
# SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# ARGS
MNT_PATH=""
INIT_SSH="0"
HOSTNAME=""
FQDN=""

usage() {
	stderr "$0 [options]"
  stderr
  stderr "Prepare a Lit OS Guest on first boot (replaces some cloud-init functions)"
  stderr
	stderr "Options:"
  stderr
	stderr " --mnt-path <PATH>  mount path for the root volume"
	stderr " --init-ssh         initialize SSH host keys"
	stderr " --hostname <STR>   hostname to set"
	stderr " --fqdn <STR>       fully qualified domain name to set"
  stderr
	exit 1
}

cleanup_on_err() {
  if [ -e "${MNT_PATH}" ]; then
    for path in "dev/pts" "dev" "proc" "sys" "run" "tmp"; do
      local cur_mnt="${MNT_PATH}/${path}"
      if [ -e "${cur_mnt}" ]; then
        if mount | grep ${cur_mnt} > /dev/null 2>&1; then
          /usr/bin/umount-full -f "${cur_mnt}" || true # Safely attempt
        fi
      fi
    done
  fi
}

ensure() {
    if ! "$@"; then die "command failed: $*"; fi
}

stderr() {
	echo "${@}" >&2
}

die() {
  stderr "${MSG_PREFIX} ERROR: ${FUNCNAME[1]}: ${@}"
  exit 1
}

info() {
  echo "${MSG_PREFIX} ${@}"
}

echo_run() {
  echo "${MSG_PREFIX} $@"
  $@
}

run_chroot_cmd() {
	local new_root=${1}
	shift

	[ -z "${new_root}" ] && die "new root directory is empty!"
	[ ${#} -eq 0 ] && die "no command specified!"

	# Mount /dev and virtual filesystems inside the chroot
	/usr/bin/mount-full --bind /dev ${new_root}/dev
	/usr/bin/mount-full --bind /dev/pts ${new_root}/dev/pts
	/usr/bin/mount-full -t proc proc ${new_root}/proc
	/usr/bin/mount-full -t sysfs sysfs ${new_root}/sys
	/usr/bin/mount-full -t tmpfs tmpfs ${new_root}/run
	/usr/bin/mount-full -t tmpfs tmpfs ${new_root}/tmp

	chroot "${new_root}" \
		/usr/bin/env -i HOME=/root TERM="${TERM}" PATH=/usr/bin:/usr/sbin DEBIAN_FRONTEND=noninteractive \
		"${@}"

	# Unmount virtual filesystems
	/usr/bin/umount-full ${new_root}/dev{/pts,}
	/usr/bin/umount-full ${new_root}/{sys,proc,run,tmp}
}

main() {
  info "Preparing Lit OS Guest on first boot..."

  if [ "${INIT_SSH}" == "1" ]; then
    info "Generating new SSH host keys..."
    run_chroot_cmd "${MNT_PATH}" dpkg-reconfigure openssh-server
  fi

  if [ -n "${HOSTNAME}" ]; then
    info "Setting hostname to: ${HOSTNAME}"

    echo "${HOSTNAME}" > "${MNT_PATH}"/var/local/etc/hostname
    {
      echo "# Generated by lit-os-init-prepare.sh"
      echo "127.0.1.1 $FQDN $HOSTNAME"
      echo "127.0.0.1 localhost"
      echo ""
      echo "# The following lines are desirable for IPv6 capable hosts"
      echo "::1 ip6-localhost ip6-loopback"
      echo "fe00::0 ip6-localnet"
      echo "ff00::0 ip6-mcastprefix"
      echo "ff02::1 ip6-allnodes"
      echo "ff02::2 ip6-allrouters"
      echo "ff02::3 ip6-allhosts"
      echo ""
      echo "# LitOS Host"
      echo "172.30.0.1 litos-host"
    } > "${MNT_PATH}"/var/local/etc/hosts
  fi

  # Set state
  touch "${MNT_PATH}/${STATE_FILE}"
}

# Run

while [ -n "$1" ]; do
	case "$1" in
		--mnt-path)  MNT_PATH="$2"
				shift
				;;
		--init-ssh)  INIT_SSH="1"
				;;
		--hostname)  HOSTNAME="$2"
				shift
				;;
		--fqdn)      FQDN="$2"
				shift
				;;
		*)
        stderr "ERROR: Invalid option: $1"
        stderr
        usage
				;;
	esac

	shift
done

if [ -z "${MNT_PATH}" ]; then
  die "Invalid: --mnt-path is required"
fi
if [ ! -e "${MNT_PATH}" ]; then
  die "Mount path not found: ${MNT_PATH}"
fi
if [ -n "${HOSTNAME}" ] || [ -n "${FQDN}" ]; then
  if [ -z "${HOSTNAME}" ] || [ -z "${FQDN}" ]; then
    die "Invalid: --hostname and --fqdn are required (or neither)"
  fi
fi

# Already run?
if [ -e "${MNT_PATH}/${STATE_FILE}" ]; then
  exit 0;
fi

main "$@"